using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace Apeiron.Services;

public sealed class LocalizationService : INotifyPropertyChanged
{
    public static LocalizationService Instance { get; } = new();

    public event PropertyChangedEventHandler? PropertyChanged;
    public event Action? LanguageChanged;

    private string _setting = "auto";
    private string _effective = "en";

    public string Setting
    {
        get => _setting;
        private set => _setting = value;
    }

    public string EffectiveLanguage => _effective;

    public string this[string key] => Get(key);

    private static readonly Dictionary<string, string> En = new()
    {
        ["common.cancel"] = "Cancel",
        ["common.save"] = "Save",
        ["common.create"] = "Create",
        ["common.error"] = "Error",
        ["common.warning"] = "Warning",
        ["common.attention"] = "Notice",
        ["common.settings"] = "Settings",
        ["common.mods"] = "Mods",
        ["common.yes"] = "Yes",
        ["common.no"] = "No",

        ["lang.auto"] = "Auto (system)",
        ["lang.en"] = "English",
        ["lang.ru"] = "Russian",

        ["main.window_title"] = "Apeiron Launcher",
        ["main.settings_tooltip"] = "Settings",
        ["main.theme_light"] = "Light theme",
        ["main.theme_dark"] = "Dark theme",
        ["main.guest"] = "Guest",
        ["main.offline_name"] = "Offline name",
        ["main.offline_name_hint"] = "3–16 characters: a-z, 0-9, _",
        ["main.offline_name_empty"] = "Enter a nickname",
        ["main.offline_name_too_short"] = "At least {0} characters",
        ["main.offline_name_invalid"] = "Only a-z, 0-9 and _ allowed",
        ["main.cancel_download"] = "Cancel",
        ["main.download_cancelled"] = "Download cancelled",
        ["main.login_prompt"] = "Sign in to play online",
        ["main.login_microsoft"] = "Sign in with Microsoft",
        ["main.logout"] = "Sign out",
        ["main.builds"] = "📦 Instances",
        ["main.add_build_tooltip"] = "Add instance",
        ["main.edit_build_tooltip"] = "Edit instance",
        ["main.console"] = "📟 Console",
        ["main.play"] = "Play",
        ["main.download"] = "Download",
        ["main.downloading"] = "Downloading...",
        ["main.launching"] = "Launching...",
        ["main.game_running"] = "Game running",
        ["main.reinstalling"] = "Reinstalling...",
        ["main.ready"] = "✅ Ready",
        ["main.cli_launch"] = "Quick launch: {0}",
        ["main.cli_build_not_found"] = "Instance not found for --launch: {0}",
        ["main.no_builds"] = "No instances. Click + to create one.",
        ["main.no_builds_short"] = "No instances",
        ["main.build_ready"] = "✅ {0} is ready to launch!",
        ["main.build_download_hint"] = "⚠️ Click «Download» to install {0}",
        ["main.select_build_edit"] = "Select an instance to edit.",
        ["main.select_build_launch"] = "Select an instance to launch.",
        ["main.launch_title"] = "Launch",
        ["main.java_required"] = "Java 17 or newer is required for Minecraft!\nInstall Java automatically?",
        ["main.java_required_title"] = "Java required",
        ["main.java_not_found_launch"] = "Java not found for this Minecraft version.\nSet the path in Settings (⚙).",
        ["main.java_not_found_title"] = "Java required",
        ["main.session_expired"] = "Microsoft session expired. Sign in again with «Sign in with Microsoft».",
        ["main.session_expired_title"] = "Sign-in required",
        ["main.settings_saved"] = "⚙️ Settings saved",
        ["main.minecraft_dir_changed"] = "Minecraft folder changed.\nRestart the launcher for changes to take effect.",
        ["main.build_created"] = "✅ Instance created: {0}",
        ["main.build_updated"] = "✅ Instance updated: {0}",
        ["main.build_deleted"] = "🗑️ Instance «{0}» deleted",
        ["main.build_copied"] = "📋 Copy created: {0}",
        ["main.auth_restored"] = "✅ Session restored: {0}",
        ["main.session_expired_console"] = "⚠️ Microsoft session expired. Sign in again to play online.",
        ["main.launch_online"] = "🔑 Launch: {0}, RAM: {1}GB, {2}",
        ["main.launch_offline"] = "👤 Offline launch, RAM: {0}GB, {1}",
        ["main.java_missing_console"] = "⚠️ Java is not installed! The game will not start.",
        ["main.console_cleared"] = "🗑️ Console cleared",
        ["main.load_builds_error"] = "❌ Failed to load instances: {0}",
        ["main.create_build_error"] = "❌ Failed to create instance: {0}",
        ["main.reinstall_status"] = "🔄 Reinstalling instance...",
        ["main.reinstall_console"] = "🔄 Reinstalling {0}...",
        ["main.profile_deleted"] = "🗑️ Profile {0} deleted",
        ["main.base_deleted"] = "🗑️ Base {0} deleted",
        ["main.reinstall_done"] = "✅ {0} reinstalled!",
        ["main.reinstall_failed"] = "❌ Failed to reinstall {0}",
        ["main.error_with_message"] = "❌ {0}",
        ["main.auth_code_status"] = "🔑 Code: {0}",
        ["main.auth_code_console"] = "🔑 Auth code: {0}",
        ["main.auth_code_url"] = "🌐 Go to {0} and enter the code",
        ["main.auth_success_status"] = "✅ Sign-in successful! {0}",
        ["main.auth_welcome"] = "✅ Welcome, {0}!",
        ["main.auth_uuid"] = "🆔 UUID: {0}",
        ["main.auth_starting_status"] = "⏳ Starting sign-in...",
        ["main.auth_starting_console"] = "🔄 Starting Microsoft sign-in...",
        ["main.auth_window_closed"] = "ℹ️ Sign-in window closed",
        ["main.logout_done"] = "✅ Signed out",
        ["main.logout_console"] = "🚪 Signed out",
        ["main.no_build_selected_log"] = "❌ No instance selected!",
        ["main.loader_unsupported"] = "Loader «{0}» is not supported.\nSupported: Fabric, Quilt, Forge, NeoForge.",
        ["main.java_required_for_launch"] = "{0} not found. Minecraft won't start without it.\n\nInstall Java automatically?",
        ["main.java_missing_status"] = "⚠️ Java is not installed!",
        ["main.install_failed"] = "Installation failed",
        ["main.install_failed_short"] = "Installation failed — see log or press «Open log»",
        ["main.session_expired_status"] = "⚠️ Session expired — sign in again",
        ["main.session_expired_console_short"] = "⚠️ Microsoft session expired. Sign in again.",
        ["main.game_launched"] = "✅ Game launched!",
        ["main.game_launched_console"] = "🚀 Game launched!",
        ["main.game_exit_code"] = "⚠️ Game exited with code {0}",
        ["main.game_closed"] = "🛑 Game closed",
        ["main.log_saved"] = "📄 Log saved: {0}",
        ["main.open_install_log"] = "Open log",
        ["main.install_log_saved"] = "Install log saved: {0}",
        ["main.install_failed_open_log"] = "Installation failed. Open the log file?",
        ["main.microsoft_account"] = "Microsoft Account",
        ["main.offline_only_mode"] = "Offline mode",
        ["main.import_modpack_tooltip"] = "Import modpack (new instance) — or drag .zip here",
        ["main.modpack_imported"] = "📦 Modpack imported: {0}",
        ["main.modpack_configure_hint"] = "Set Minecraft version and loader in instance settings, then install.",
        ["main.modpack_drop_invalid"] = "Drop a .zip modpack file to import a new instance.",

        ["settings.title"] = "Settings",
        ["settings.ram"] = "RAM (GB)",
        ["settings.language"] = "Language",
        ["settings.java"] = "Java",
        ["settings.java_hint"] = "Empty — auto (by MC version)",
        ["settings.java_browse"] = "Select java.exe",
        ["settings.mc_folder"] = "MC folder",
        ["settings.mc_hint"] = "Empty — .minecraft next to launcher",
        ["settings.mc_browse"] = ".minecraft folder",
        ["settings.open_logs"] = "Open logs",
        ["settings.ram_invalid"] = "RAM must be between 1 and {0} GB.",
        ["settings.java_not_found"] = "Java file not found.",
        ["settings.folder_missing"] = "Folder does not exist:\n{0}\n\nCreate it?",
        ["settings.version"] = "Apeiron Launcher v{0}",
        ["settings.offline_only"] = "Offline mode only (hide Microsoft sign-in)",
        ["settings.check_updates"] = "Check for updates on startup",
        ["settings.check_updates_now"] = "Check for updates",
        ["settings.update_not_configured"] = "Update source is not configured in this build.",
        ["settings.update_none"] = "You are running the latest version.",
        ["settings.update_available"] = "Version {0} is available (current: {1}).\n\nDownload and restart now?",

        ["add_build.title"] = "New instance",
        ["add_build.window_title"] = "Create instance",
        ["add_build.name"] = "Name",
        ["add_build.name_hint"] = "Optional — filled in automatically",
        ["add_build.type"] = "Type",
        ["add_build.type.vanilla"] = "Vanilla",
        ["add_build.type.modded"] = "Modded",
        ["add_build.loader"] = "Mod loader",
        ["add_build.mc_version"] = "MC version",
        ["add_build.search_versions"] = "Search",
        ["add_build.search_versions_hint"] = "e.g. 1.20",
        ["add_build.no_search_results"] = "No versions match «{0}»",
        ["add_build.filter"] = "Filter",
        ["add_build.show_snapshots"] = "Show snapshots and pre-releases",
        ["add_build.loader_version"] = "Version",
        ["add_build.refresh_versions"] = "Refresh version list",
        ["add_build.loading"] = "Loading...",
        ["add_build.no_versions"] = "No versions",
        ["add_build.no_stable_versions"] = "No stable versions",
        ["add_build.no_loader_versions"] = "No versions available",
        ["add_build.load_versions_error"] = "Failed to load versions: {0}",
        ["add_build.select_mc_version"] = "Select a Minecraft version.",
        ["add_build.select_loader_version"] = "Select a loader version.",
        ["add_build.type.snapshot"] = "snapshot",
        ["add_build.type.beta"] = "beta",
        ["add_build.type.alpha"] = "alpha",
        ["add_build.type.prerelease"] = "pre-release",

        ["edit_build.title"] = "Edit instance",
        ["edit_build.window_title"] = "Edit instance",
        ["edit_build.name"] = "Name",
        ["edit_build.profile"] = "Profile",
        ["edit_build.mods"] = "Mods",
        ["edit_build.mods_enabled"] = "Use mods",
        ["edit_build.mods_list"] = "List",
        ["edit_build.add_mod"] = "Add mod",
        ["edit_build.open_mods_folder"] = "Open folder",
        ["edit_build.refresh_mods"] = "Refresh",
        ["edit_build.no_mods"] = "No mods. Drag .jar files here or click «Add mod».",
        ["edit_build.no_mods_match"] = "No mods match the search.",
        ["edit_build.mod_search_tooltip"] = "Search by name or version",
        ["edit_build.launch"] = "Launch",
        ["edit_build.default_build"] = "Primary instance (selected on startup)",
        ["edit_build.jvm"] = "JVM",
        ["edit_build.jvm_tooltip"] = "Extra Java flags, e.g. -XX:+UseG1GC",
        ["edit_build.window"] = "Window",
        ["edit_build.width_tooltip"] = "Width (empty = default)",
        ["edit_build.height_tooltip"] = "Height (empty = default)",
        ["edit_build.fullscreen"] = "Fullscreen",
        ["edit_build.folder"] = "Folder",
        ["edit_build.folder_tooltip"] = "Open instance folder",
        ["edit_build.duplicate"] = "Duplicate",
        ["edit_build.reinstall"] = "Reinstall",
        ["edit_build.delete"] = "Delete",
        ["edit_build.reinstall_confirm"] = "Reinstall «{0}»?\n\nThe version profile will be removed and downloaded again. Mods are not affected.",
        ["edit_build.reinstall_title"] = "Confirm",
        ["edit_build.duplicate_confirm"] = "Duplicate «{0}»?\n\nMods and configs will be copied. Worlds (saves) will not.",
        ["edit_build.duplicate_title"] = "Duplicate instance",
        ["edit_build.delete_confirm"] = "Delete instance «{0}»?\n\nThe instance folder and all data will be permanently deleted.",
        ["edit_build.delete_title"] = "Confirm deletion",
        ["edit_build.mods_added"] = "Mods added: {0}",
        ["edit_build.select_mods"] = "Select mods",
        ["edit_build.mod_filter"] = "JAR mods (*.jar)|*.jar",
        ["edit_build.export"] = "Export",
        ["edit_build.import"] = "Import",
        ["edit_build.export_title"] = "Export instance",
        ["edit_build.import_title"] = "Import into instance",
        ["edit_build.export_filter"] = "ZIP archive (*.zip)|*.zip",
        ["edit_build.export_done"] = "Instance exported successfully.",
        ["edit_build.import_done"] = "Data imported into the instance.",
        ["edit_build.ram"] = "RAM (GB)",
        ["edit_build.ram_use_global"] = "Use global",
        ["edit_build.ram_tooltip"] = "Instance RAM; uncheck to override global setting",
        ["edit_build.backup"] = "Full backup",
        ["edit_build.backup_tooltip"] = "Export mods, config, and saves",
        ["edit_build.backup_title"] = "Full instance backup",
        ["edit_build.backup_done"] = "Full backup exported successfully.",

        ["auth.title"] = "Microsoft sign-in",
        ["auth.processing"] = "Completing sign-in...",
        ["auth.heading"] = "🔐 Sign in with Microsoft",
        ["auth.subtitle"] = "Sign in with your Microsoft account to play with a license",
        ["auth.init_error"] = "Authorization init error: {0}",
        ["auth.server_html"] = "Server returned HTML. Check your connection.",
        ["auth.error_status"] = "Error: {0}",
        ["auth.no_auth_code"] = "Failed to get authorization code",
        ["auth.no_token"] = "Failed to get token",
        ["auth.cancelled"] = "Sign-in cancelled",
        ["auth.timeout"] = "Sign-in timed out",
        ["auth.error_description"] = "Error: {0}",
        ["auth.code_empty"] = "Authorization code is empty",
        ["auth.token_error"] = "Token error: {0}",
        ["auth.xbox_error"] = "Xbox Live sign-in error",
        ["auth.xbox_no_token"] = "Failed to get Xbox Live token",
        ["auth.xsts_error"] = "XSTS sign-in error",
        ["auth.mc_auth_error"] = "Minecraft sign-in error",
        ["auth.profile_error"] = "Failed to get profile",
        ["auth.default_player"] = "Player",

        ["build.copy_suffix"] = " (copy)",
        ["build.duplicate_exists"] = "An instance named «{0}» already exists",
        ["build.not_found"] = "Instance not found",
        ["build.delete_folder_failed"] = "Failed to delete instance folder: {0}",

        ["java.install_prompt"] = "Java 25 is required for Minecraft 26.1!\n\nInstall Java 25 automatically?",
        ["java.install_title"] = "Java required",
        ["java.installed_restart"] = "Java 25 installed!\nThe launcher will restart.",
        ["java.installed_title"] = "Java",
        ["java.downloaded_install_prompt"] = "Java 25 downloaded.\n\nInstall automatically?",
        ["java.install_dialog_title"] = "Installing Java 25",
        ["java.install_success_title"] = "Success",
        ["java.installed_system"] = "Java {0} installed on Windows. It is available to all programs.",
        ["auth.token_load_error"] = "Error loading token: {0}",
        ["auth.token_save_error"] = "Error saving token: {0}",

        ["log.download_file"] = "Downloading {0}...",
        ["log.mc.launcher_dir"] = "📁 Launcher folder: {0}",
        ["log.mc.minecraft_dir"] = "📁 Minecraft folder: {0}",
        ["log.mc.downloading"] = "📥 Downloading Minecraft {0}...",
        ["log.mc.already_downloaded"] = "✅ Minecraft {0} already downloaded",
        ["log.mc.downloading_manifest"] = "⬇️ Downloading manifest...",
        ["log.mc.version_not_in_manifest"] = "❌ Version {0} not found in manifest",
        ["log.mc.version_url_not_found"] = "❌ URL for version {0} not found",
        ["log.mc.downloading_version_json"] = "⬇️ Downloading {0}.json...",
        ["log.mc.client_jar_url_not_found"] = "❌ URL for client.jar not found",
        ["log.mc.downloading_client_jar"] = "⬇️ Downloading client.jar...",
        ["log.mc.downloading_library"] = "Downloading library {0}...",
        ["log.mc.downloading_lwjgl_unsafe"] = "⬇️ Downloading lwjgl-unsafe (required for LWJGL)...",
        ["log.mc.download_cancelled"] = "Download cancelled",
        ["log.mc.sha1_mismatch"] = "SHA1 checksum mismatch",
        ["log.mc.downloading_asset_index"] = "⬇️ Downloading asset index...",
        ["log.mc.downloading_all_assets"] = "⏳ DOWNLOADING ALL ASSETS (this will take a while)...",
        ["log.mc.ready"] = "✅ Minecraft {0} ready!",
        ["log.mc.download_error"] = "❌ Minecraft download error: {0}",
        ["log.mc.retry"] = "⚠️ Download error, retry {0}/{1}: {2}",
        ["log.mc.downloading_all_assets_start"] = "📦 Downloading all assets...",
        ["log.mc.index_file_not_found"] = "❌ Index file not found: {0}",
        ["log.mc.no_objects_in_index"] = "❌ No objects in index",
        ["log.mc.assets_total"] = "📊 Total assets to download: {0}",
        ["log.mc.downloading_assets"] = "Downloading assets ({0}/{1})...",
        ["log.mc.assets_done"] = "✅ All assets downloaded ({0}/{1})",
        ["log.mc.assets_partial_fail"] = "❌ Failed to download {0} of {1} assets",
        ["log.mc.assets_error"] = "❌ Asset download error: {0}",
        ["log.mc.download_file_error"] = "⚠️ Download error {0}: {1}",
        ["log.mc.no_asset_index"] = "❌ No assetIndex in version {0}",
        ["log.mc.no_asset_index_url"] = "❌ No URL for assetIndex",
        ["log.mc.index_download_error"] = "❌ Index download error: {0}",
        ["log.mc.virtual_assets_error"] = "❌ ERROR: {0}",
        ["log.launch.classpath_failed"] = "❌ Failed to build classpath",
        ["log.launch.java_not_found"] = "❌ Java not found",
        ["log.launch.main_class_not_found"] = "❌ mainClass not found in version profile",
        ["log.launch.starting"] = "🚀 Launching {0}...",
        ["log.launch.using_java"] = "☕ Java {1}: {0}",
        ["log.launch.started"] = "✅ Game started ({0})",
        ["log.launch.error"] = "❌ Launch error: {0}",
        ["log.launch.version_profile_not_found"] = "Version profile not found: {0}",
        ["log.launch.natives_error"] = "⚠️ Natives {0}: {1}",
        ["log.launch.library_verify_failed"] = "Library integrity check failed: {0}",
        ["log.java.downloading"] = "Downloading Oracle Java {0}...",
        ["log.java.downloading_progress"] = "Downloading Oracle Java {0}...",
        ["log.java.installing"] = "Installing Oracle Java {0}...",
        ["log.java.installed"] = "✅ Java {0} installed!",
        ["log.java.trying_mirror"] = "⬇️ Download source {0}/{1}...",
        ["log.java.mirror_failed"] = "⚠️ Source {0} failed: {1}",
        ["log.java.download_failed"] = "❌ Could not download Java {0} from any mirror. Check your internet or install JDK manually.",
        ["log.java.installed_system"] = "Oracle Java {0} ready",
        ["log.java.install_cancelled"] = "⚠️ Java installation cancelled (admin permission required)",
        ["log.java.invalid_installer"] = "⚠️ Downloaded file is not a valid Java installer, trying next source...",
        ["log.java.installing_zip"] = "⚙️ Installing Java {0} to {1}...",
        ["log.java.installed_restart_hint"] = "⚠️ Java {0} installed. Restart the launcher if it is not detected.",
        ["log.java.extract_failed"] = "❌ Failed to extract Java archive",
        ["log.java.install_exit_code"] = "⚠️ Installation finished with code {0}",
        ["log.build.installing"] = "📥 Installing instance «{0}»...",
        ["log.build.ready"] = "✅ Instance «{0}» is ready!",
        ["progress.install.mc"] = "Downloading Minecraft {0}...",
        ["progress.install.loader"] = "Installing {0} {1}...",
        ["progress.install.fabric_api"] = "Installing Fabric API...",
        ["progress.install.ready"] = "Ready to launch",
        ["log.builds.load_error"] = "Error loading instances: {0}",
        ["log.builds.save_error"] = "Error saving instances: {0}",
        ["log.builds.corrupt"] = "Instances file is corrupt: {0}",
        ["log.builds.corrupt_backup"] = "Corrupt instances file backed up to: {0}",
        ["log.loader.version_not_specified"] = "❌ Loader version not specified",
        ["log.loader.unsupported"] = "❌ Loader {0} is not supported.",
        ["log.loader.minecraft_first"] = "❌ Minecraft {0} must be downloaded first",
        ["log.loader.already_installed"] = "✅ {0} {1} for {2} already installed",
        ["log.loader.installing"] = "🔨 Installing {0} {1} for Minecraft {2}...",
        ["log.loader.downloading_installer"] = "⬇️ Downloading {0} Installer...",
        ["log.loader.installer_exit_code"] = "⚠️ {0} Installer finished with code {1}",
        ["log.loader.installed"] = "✅ {0} {1} installed",
        ["log.loader.installed_resolved"] = "✅ {0} {1} installed ({2})",
        ["log.loader.installer_no_profile"] = "❌ {0} Installer did not create version profile",
        ["log.loader.install_error"] = "❌ {0} installation error: {1}",
        ["log.loader.fabric_installing"] = "🧵 Installing Fabric {0} for Minecraft {1}...",
        ["log.loader.quilt_installing"] = "🧵 Installing Quilt {0} for Minecraft {1}...",
        ["log.loader.installer_fallback"] = "⚠️ Installer failed, downloading profile directly...",
        ["log.loader.running_installer"] = "⚙️ Running {0} Installer...",
        ["log.loader.installer_warning"] = "⚠️ {0} Installer: {1}",
        ["log.loader.invalid_version_jar"] = "Version jar is missing or corrupt: {0}",
        ["log.loader.quilt_installer_version_error"] = "❌ Failed to get Quilt Installer version",
        ["log.loader.launcher_profiles_created"] = "📄 Created launcher_profiles.json for installer",
        ["log.fabric.already_installed"] = "✅ Fabric API already installed",
        ["log.fabric.downloading"] = "📥 Downloading Fabric API...",
        ["log.fabric.not_found"] = "⚠️ Fabric API not found for this MC version",
        ["log.fabric.url_not_found"] = "⚠️ Failed to get Fabric API download link",
        ["log.fabric.installed"] = "✅ Fabric API installed: {0}",
        ["log.fabric.error"] = "⚠️ Fabric API: {0}",
        ["log.session_start"] = "=== Launcher session ===",
        ["log.game_saved"] = "Game log saved: {0}",
        ["log.install_saved"] = "Install log saved: {0}",
        ["log.settings.load_error"] = "Failed to load settings: {0}",
        ["log.settings.save_error"] = "Failed to save settings: {0}",
    };

    private static readonly Dictionary<string, string> Ru = new()
    {
        ["common.cancel"] = "Отмена",
        ["common.save"] = "Сохранить",
        ["common.create"] = "Создать",
        ["common.error"] = "Ошибка",
        ["common.warning"] = "Внимание",
        ["common.attention"] = "Внимание",
        ["common.settings"] = "Настройки",
        ["common.mods"] = "Моды",
        ["common.yes"] = "Да",
        ["common.no"] = "Нет",

        ["lang.auto"] = "Авто (система)",
        ["lang.en"] = "English",
        ["lang.ru"] = "Русский",

        ["main.window_title"] = "Apeiron Launcher",
        ["main.settings_tooltip"] = "Настройки",
        ["main.theme_light"] = "Светлая тема",
        ["main.theme_dark"] = "Тёмная тема",
        ["main.guest"] = "Гость",
        ["main.offline_name"] = "Офлайн-ник",
        ["main.offline_name_hint"] = "3–16 символов: a-z, 0-9, _",
        ["main.offline_name_empty"] = "Введите ник",
        ["main.offline_name_too_short"] = "Минимум {0} символа",
        ["main.offline_name_invalid"] = "Только a-z, 0-9 и _",
        ["main.cancel_download"] = "Отмена",
        ["main.download_cancelled"] = "Загрузка отменена",
        ["main.login_prompt"] = "Войдите для игры онлайн",
        ["main.login_microsoft"] = "Войти через Microsoft",
        ["main.logout"] = "Выйти",
        ["main.builds"] = "📦 Сборки",
        ["main.add_build_tooltip"] = "Добавить сборку",
        ["main.edit_build_tooltip"] = "Редактировать сборку",
        ["main.console"] = "📟 Консоль",
        ["main.play"] = "Играть",
        ["main.download"] = "Скачать",
        ["main.downloading"] = "Скачивание...",
        ["main.launching"] = "Запуск...",
        ["main.game_running"] = "Игра запущена",
        ["main.reinstalling"] = "Переустановка...",
        ["main.ready"] = "✅ Готов к работе",
        ["main.cli_launch"] = "Быстрый запуск: {0}",
        ["main.cli_build_not_found"] = "Сборка не найдена для --launch: {0}",
        ["main.no_builds"] = "Нет сборок. Нажмите + для создания.",
        ["main.no_builds_short"] = "Нет сборок",
        ["main.build_ready"] = "✅ {0} готова к запуску!",
        ["main.build_download_hint"] = "⚠️ Нажмите «Скачать» для установки {0}",
        ["main.select_build_edit"] = "Выберите сборку для редактирования.",
        ["main.select_build_launch"] = "Выберите сборку для запуска.",
        ["main.launch_title"] = "Запуск",
        ["main.java_required"] = "Для Minecraft требуется Java 17 или новее!\nУстановить Java автоматически?",
        ["main.java_required_title"] = "Требуется Java",
        ["main.java_not_found_launch"] = "Не найдена Java для этой версии MC.\nУкажите путь в настройках (⚙).",
        ["main.java_not_found_title"] = "Требуется Java",
        ["main.session_expired"] = "Сессия Microsoft истекла. Войдите снова через кнопку «Войти через Microsoft».",
        ["main.session_expired_title"] = "Требуется авторизация",
        ["main.settings_saved"] = "⚙️ Настройки сохранены",
        ["main.minecraft_dir_changed"] = "Папка Minecraft изменена.\nПерезапустите лаунчер, чтобы изменения вступили в силу.",
        ["main.build_created"] = "✅ Сборка создана: {0}",
        ["main.build_updated"] = "✅ Сборка обновлена: {0}",
        ["main.build_deleted"] = "🗑️ Сборка «{0}» удалена",
        ["main.build_copied"] = "📋 Создана копия: {0}",
        ["main.auth_restored"] = "✅ Авторизация восстановлена: {0}",
        ["main.session_expired_console"] = "⚠️ Сессия Microsoft истекла. Войдите снова для игры онлайн.",
        ["main.launch_online"] = "🔑 Запуск: {0}, RAM: {1}GB, {2}",
        ["main.launch_offline"] = "👤 Офлайн-запуск, RAM: {0}GB, {1}",
        ["main.java_missing_console"] = "⚠️ Java не установлена! Игра не запустится.",
        ["main.console_cleared"] = "🗑️ Консоль очищена",
        ["main.load_builds_error"] = "❌ Ошибка загрузки сборок: {0}",
        ["main.create_build_error"] = "❌ Ошибка создания сборки: {0}",
        ["main.reinstall_status"] = "🔄 Переустановка сборки...",
        ["main.reinstall_console"] = "🔄 Переустановка {0}...",
        ["main.profile_deleted"] = "🗑️ Профиль {0} удалён",
        ["main.base_deleted"] = "🗑️ База {0} удалена",
        ["main.reinstall_done"] = "✅ {0} переустановлена!",
        ["main.reinstall_failed"] = "❌ Ошибка переустановки {0}",
        ["main.error_with_message"] = "❌ {0}",
        ["main.auth_code_status"] = "🔑 Код: {0}",
        ["main.auth_code_console"] = "🔑 Код авторизации: {0}",
        ["main.auth_code_url"] = "🌐 Перейдите на {0} и введите код",
        ["main.auth_success_status"] = "✅ Авторизация успешна! {0}",
        ["main.auth_welcome"] = "✅ Добро пожаловать, {0}!",
        ["main.auth_uuid"] = "🆔 UUID: {0}",
        ["main.auth_starting_status"] = "⏳ Запуск авторизации...",
        ["main.auth_starting_console"] = "🔄 Начинаем процесс авторизации через Microsoft...",
        ["main.auth_window_closed"] = "ℹ️ Окно авторизации закрыто",
        ["main.logout_done"] = "✅ Выход выполнен",
        ["main.logout_console"] = "🚪 Выход из аккаунта",
        ["main.no_build_selected_log"] = "❌ Не выбрана сборка!",
        ["main.loader_unsupported"] = "Лоадер «{0}» не поддерживается.\nПоддерживаются: Fabric, Quilt, Forge, NeoForge.",
        ["main.java_required_for_launch"] = "{0} не найдена. Minecraft не запустится без неё.\n\nУстановить Java автоматически?",
        ["main.java_missing_status"] = "⚠️ Java не установлена!",
        ["main.install_failed"] = "Ошибка установки",
        ["main.install_failed_short"] = "Ошибка установки — смотрите лог или «Открыть лог»",
        ["main.session_expired_status"] = "⚠️ Сессия истекла — войдите снова",
        ["main.session_expired_console_short"] = "⚠️ Сессия Microsoft истекла. Повторите вход.",
        ["main.game_launched"] = "✅ Игра запущена!",
        ["main.game_launched_console"] = "🚀 Игра запущена!",
        ["main.game_exit_code"] = "⚠️ Игра завершилась с кодом {0}",
        ["main.game_closed"] = "🛑 Игра закрыта",
        ["main.log_saved"] = "📄 Лог сохранён: {0}",
        ["main.open_install_log"] = "Открыть лог",
        ["main.install_log_saved"] = "Лог установки сохранён: {0}",
        ["main.install_failed_open_log"] = "Ошибка установки. Открыть файл лога?",
        ["main.microsoft_account"] = "Аккаунт Microsoft",
        ["main.offline_only_mode"] = "Офлайн-режим",
        ["main.import_modpack_tooltip"] = "Импорт модпака (новая сборка) — или перетащите .zip",
        ["main.modpack_imported"] = "📦 Модпак импортирован: {0}",
        ["main.modpack_configure_hint"] = "Укажите версию Minecraft и лоадер в настройках сборки, затем установите.",
        ["main.modpack_drop_invalid"] = "Перетащите .zip модпака для импорта новой сборки.",

        ["settings.title"] = "Настройки",
        ["settings.ram"] = "RAM (ГБ)",
        ["settings.language"] = "Язык",
        ["settings.java"] = "Java",
        ["settings.java_hint"] = "Пусто — авто (по версии MC)",
        ["settings.java_browse"] = "Выберите java.exe",
        ["settings.mc_folder"] = "Папка MC",
        ["settings.mc_hint"] = "Пусто — .minecraft рядом с лаунчером",
        ["settings.mc_browse"] = "Папка .minecraft",
        ["settings.open_logs"] = "Открыть логи",
        ["settings.ram_invalid"] = "RAM должна быть от 1 до {0} ГБ.",
        ["settings.java_not_found"] = "Файл Java не найден.",
        ["settings.folder_missing"] = "Папка не существует:\n{0}\n\nСоздать?",
        ["settings.version"] = "Apeiron Launcher v{0}",
        ["settings.offline_only"] = "Только офлайн (скрыть вход Microsoft)",
        ["settings.check_updates"] = "Проверять обновления при запуске",
        ["settings.check_updates_now"] = "Проверить обновления",
        ["settings.update_not_configured"] = "Источник обновлений не настроен в этой сборке.",
        ["settings.update_none"] = "Установлена последняя версия.",
        ["settings.update_available"] = "Доступна версия {0} (текущая: {1}).\n\nСкачать и перезапустить?",

        ["add_build.title"] = "Новая сборка",
        ["add_build.window_title"] = "Создание сборки",
        ["add_build.name"] = "Название",
        ["add_build.name_hint"] = "Необязательно — подставится автоматически",
        ["add_build.type"] = "Тип",
        ["add_build.type.vanilla"] = "Ванильная",
        ["add_build.type.modded"] = "Модовая",
        ["add_build.loader"] = "Модлоадер",
        ["add_build.mc_version"] = "Версия MC",
        ["add_build.search_versions"] = "Поиск",
        ["add_build.search_versions_hint"] = "например 1.20",
        ["add_build.no_search_results"] = "Нет версий по запросу «{0}»",
        ["add_build.filter"] = "Фильтр",
        ["add_build.show_snapshots"] = "Показывать снапшоты и pre-release",
        ["add_build.loader_version"] = "Версия",
        ["add_build.refresh_versions"] = "Обновить список версий",
        ["add_build.loading"] = "Загрузка...",
        ["add_build.no_versions"] = "Нет версий",
        ["add_build.no_stable_versions"] = "Нет стабильных версий",
        ["add_build.no_loader_versions"] = "Нет доступных версий",
        ["add_build.load_versions_error"] = "Ошибка загрузки версий: {0}",
        ["add_build.select_mc_version"] = "Выберите версию Minecraft.",
        ["add_build.select_loader_version"] = "Выберите версию загрузчика.",
        ["add_build.type.snapshot"] = "снапшот",
        ["add_build.type.beta"] = "beta",
        ["add_build.type.alpha"] = "alpha",
        ["add_build.type.prerelease"] = "pre-release",

        ["edit_build.title"] = "Редактирование сборки",
        ["edit_build.window_title"] = "Редактирование сборки",
        ["edit_build.name"] = "Название",
        ["edit_build.profile"] = "Профиль",
        ["edit_build.mods"] = "Моды",
        ["edit_build.mods_enabled"] = "Использовать моды",
        ["edit_build.mods_list"] = "Список",
        ["edit_build.add_mod"] = "Добавить мод",
        ["edit_build.open_mods_folder"] = "Открыть папку",
        ["edit_build.refresh_mods"] = "Обновить",
        ["edit_build.no_mods"] = "Нет модов. Перетащите .jar сюда или нажмите «Добавить мод».",
        ["edit_build.no_mods_match"] = "Нет модов по запросу.",
        ["edit_build.mod_search_tooltip"] = "Поиск по имени или версии",
        ["edit_build.launch"] = "Запуск",
        ["edit_build.default_build"] = "Основная сборка (выбирается при старте)",
        ["edit_build.jvm"] = "JVM",
        ["edit_build.jvm_tooltip"] = "Дополнительные флаги Java, например: -XX:+UseG1GC",
        ["edit_build.window"] = "Окно",
        ["edit_build.width_tooltip"] = "Ширина (пусто = по умолчанию)",
        ["edit_build.height_tooltip"] = "Высота (пусто = по умолчанию)",
        ["edit_build.fullscreen"] = "Полный экран",
        ["edit_build.folder"] = "Папка",
        ["edit_build.folder_tooltip"] = "Открыть папку сборки",
        ["edit_build.duplicate"] = "Дублировать",
        ["edit_build.reinstall"] = "Переустановить",
        ["edit_build.delete"] = "Удалить",
        ["edit_build.reinstall_confirm"] = "Переустановить «{0}»?\n\nПрофиль версии будет удалён и скачан заново. Моды не затрагиваются.",
        ["edit_build.reinstall_title"] = "Подтверждение",
        ["edit_build.duplicate_confirm"] = "Дублировать «{0}»?\n\nМоды и конфиги будут скопированы. Миры (saves) — нет.",
        ["edit_build.duplicate_title"] = "Дублирование сборки",
        ["edit_build.delete_confirm"] = "Удалить сборку «{0}»?\n\nПапка инстанса и все данные сборки будут удалены безвозвратно.",
        ["edit_build.delete_title"] = "Подтверждение удаления",
        ["edit_build.mods_added"] = "Добавлено модов: {0}",
        ["edit_build.select_mods"] = "Выберите моды",
        ["edit_build.mod_filter"] = "JAR-моды (*.jar)|*.jar",
        ["edit_build.export"] = "Экспорт",
        ["edit_build.import"] = "Импорт",
        ["edit_build.export_title"] = "Экспорт сборки",
        ["edit_build.import_title"] = "Импорт в сборку",
        ["edit_build.export_filter"] = "ZIP-архив (*.zip)|*.zip",
        ["edit_build.export_done"] = "Сборка экспортирована.",
        ["edit_build.import_done"] = "Данные импортированы в сборку.",
        ["edit_build.ram"] = "RAM (ГБ)",
        ["edit_build.ram_use_global"] = "Глобальная",
        ["edit_build.ram_tooltip"] = "RAM сборки; снимите галочку для своего значения",
        ["edit_build.backup"] = "Полный бэкап",
        ["edit_build.backup_tooltip"] = "Экспорт модов, конфига и миров",
        ["edit_build.backup_title"] = "Полный бэкап сборки",
        ["edit_build.backup_done"] = "Полный бэкап экспортирован.",

        ["auth.title"] = "Авторизация Microsoft",
        ["auth.processing"] = "Завершение входа...",
        ["auth.heading"] = "🔐 Вход через Microsoft",
        ["auth.subtitle"] = "Войдите в свой аккаунт Microsoft, чтобы играть с лицензией",
        ["auth.init_error"] = "Ошибка инициализации авторизации: {0}",
        ["auth.server_html"] = "Сервер вернул HTML. Проверьте подключение.",
        ["auth.error_status"] = "Ошибка: {0}",
        ["auth.no_auth_code"] = "Не удалось получить код авторизации",
        ["auth.no_token"] = "Не удалось получить токен",
        ["auth.cancelled"] = "Авторизация отменена пользователем",
        ["auth.timeout"] = "Время авторизации истекло",
        ["auth.error_description"] = "Ошибка: {0}",
        ["auth.code_empty"] = "Код авторизации пуст",
        ["auth.token_error"] = "Ошибка получения токена: {0}",
        ["auth.xbox_error"] = "Ошибка Xbox Live авторизации",
        ["auth.xbox_no_token"] = "Не удалось получить токен Xbox Live",
        ["auth.xsts_error"] = "Ошибка XSTS авторизации",
        ["auth.mc_auth_error"] = "Ошибка Minecraft авторизации",
        ["auth.profile_error"] = "Ошибка получения профиля",
        ["auth.default_player"] = "Игрок",

        ["build.copy_suffix"] = " (копия)",
        ["build.duplicate_exists"] = "Сборка с именем «{0}» уже существует",
        ["build.not_found"] = "Сборка не найдена",
        ["build.delete_folder_failed"] = "Не удалось удалить папку сборки: {0}",

        ["java.install_prompt"] = "Для Minecraft 26.1 требуется Java 25!\n\nУстановить Java 25 автоматически?",
        ["java.install_title"] = "Требуется Java",
        ["java.installed_restart"] = "Java 25 установлена!\nЛаунчер будет перезапущен.",
        ["java.installed_title"] = "Java",
        ["java.downloaded_install_prompt"] = "Java 25 скачана.\n\nУстановить автоматически?",
        ["java.install_dialog_title"] = "Установка Java 25",
        ["java.install_success_title"] = "Успешно",
        ["java.installed_system"] = "Java {0} установлена в Windows. Доступна всем программам.",
        ["auth.token_load_error"] = "Ошибка загрузки токена: {0}",
        ["auth.token_save_error"] = "Ошибка сохранения токена: {0}",

        ["log.download_file"] = "Скачивание {0}...",
        ["log.mc.launcher_dir"] = "📁 Папка лаунчера: {0}",
        ["log.mc.minecraft_dir"] = "📁 Папка Minecraft: {0}",
        ["log.mc.downloading"] = "📥 Загрузка Minecraft {0}...",
        ["log.mc.already_downloaded"] = "✅ Minecraft {0} уже скачан",
        ["log.mc.downloading_manifest"] = "⬇️ Скачивание манифеста...",
        ["log.mc.version_not_in_manifest"] = "❌ Версия {0} не найдена в манифесте",
        ["log.mc.version_url_not_found"] = "❌ URL для версии {0} не найден",
        ["log.mc.downloading_version_json"] = "⬇️ Скачивание {0}.json...",
        ["log.mc.client_jar_url_not_found"] = "❌ URL для client.jar не найден",
        ["log.mc.downloading_client_jar"] = "⬇️ Скачивание client.jar...",
        ["log.mc.downloading_library"] = "Скачивание библиотеки {0}...",
        ["log.mc.downloading_lwjgl_unsafe"] = "⬇️ Скачивание lwjgl-unsafe (нужен для LWJGL)...",
        ["log.mc.download_cancelled"] = "Загрузка отменена",
        ["log.mc.sha1_mismatch"] = "Несовпадение контрольной суммы SHA1",
        ["log.mc.downloading_asset_index"] = "⬇️ Скачивание asset index...",
        ["log.mc.downloading_all_assets"] = "⏳ СКАЧИВАНИЕ ВСЕХ АССЕТОВ (это займёт время)...",
        ["log.mc.ready"] = "✅ Minecraft {0} готов!",
        ["log.mc.download_error"] = "❌ Ошибка загрузки Minecraft: {0}",
        ["log.mc.retry"] = "⚠️ Ошибка скачивания, повтор {0}/{1}: {2}",
        ["log.mc.downloading_all_assets_start"] = "📦 Скачивание всех ассетов...",
        ["log.mc.index_file_not_found"] = "❌ Файл индекса не найден: {0}",
        ["log.mc.no_objects_in_index"] = "❌ В индексе нет объектов",
        ["log.mc.assets_total"] = "📊 Всего ассетов для скачивания: {0}",
        ["log.mc.downloading_assets"] = "Скачивание ассетов ({0}/{1})...",
        ["log.mc.assets_done"] = "✅ Все ассеты скачаны ({0}/{1})",
        ["log.mc.assets_partial_fail"] = "❌ Не удалось скачать {0} из {1} ассетов",
        ["log.mc.assets_error"] = "❌ Ошибка скачивания ассетов: {0}",
        ["log.mc.download_file_error"] = "⚠️ Ошибка скачивания {0}: {1}",
        ["log.mc.no_asset_index"] = "❌ Нет assetIndex в версии {0}",
        ["log.mc.no_asset_index_url"] = "❌ Нет URL для assetIndex",
        ["log.mc.index_download_error"] = "❌ Ошибка скачивания индекса: {0}",
        ["log.mc.virtual_assets_error"] = "❌ ОШИБКА: {0}",
        ["log.launch.classpath_failed"] = "❌ Не удалось собрать classpath",
        ["log.launch.java_not_found"] = "❌ Java не найдена",
        ["log.launch.main_class_not_found"] = "❌ mainClass не найден в профиле версии",
        ["log.launch.starting"] = "🚀 Запуск {0}...",
        ["log.launch.using_java"] = "☕ Java {1}: {0}",
        ["log.launch.started"] = "✅ Игра запущена ({0})",
        ["log.launch.error"] = "❌ Ошибка запуска: {0}",
        ["log.launch.version_profile_not_found"] = "Профиль версии не найден: {0}",
        ["log.launch.natives_error"] = "⚠️ Natives {0}: {1}",
        ["log.launch.library_verify_failed"] = "Ошибка проверки целостности библиотеки: {0}",
        ["log.java.downloading"] = "Загрузка Oracle Java {0}...",
        ["log.java.downloading_progress"] = "Скачивание Oracle Java {0}...",
        ["log.java.installing"] = "Установка Oracle Java {0}...",
        ["log.java.installed"] = "✅ Java {0} установлена!",
        ["log.java.trying_mirror"] = "⬇️ Источник загрузки {0}/{1}...",
        ["log.java.mirror_failed"] = "⚠️ Источник {0} недоступен: {1}",
        ["log.java.download_failed"] = "❌ Не удалось скачать Java {0} ни с одного зеркала. Проверьте интернет или установите JDK вручную.",
        ["log.java.installed_system"] = "Oracle Java {0} готова",
        ["log.java.install_cancelled"] = "⚠️ Установка Java отменена (нужны права администратора)",
        ["log.java.invalid_installer"] = "⚠️ Скачанный файл не является установщиком Java, пробуем другой источник...",
        ["log.java.installing_zip"] = "⚙️ Установка Java {0} в {1}...",
        ["log.java.installed_restart_hint"] = "⚠️ Java {0} установлена. Перезапустите лаунчер, если она не определилась.",
        ["log.java.extract_failed"] = "❌ Не удалось распаковать архив Java",
        ["log.java.install_exit_code"] = "⚠️ Установка завершилась с кодом {0}",
        ["log.build.installing"] = "📥 Установка сборки «{0}»...",
        ["log.build.ready"] = "✅ Сборка «{0}» готова!",
        ["progress.install.mc"] = "Скачивание Minecraft {0}...",
        ["progress.install.loader"] = "Установка {0} {1}...",
        ["progress.install.fabric_api"] = "Установка Fabric API...",
        ["progress.install.ready"] = "Готово к запуску",
        ["log.builds.load_error"] = "Ошибка загрузки сборок: {0}",
        ["log.builds.save_error"] = "Ошибка сохранения сборок: {0}",
        ["log.builds.corrupt"] = "Файл сборок повреждён: {0}",
        ["log.builds.corrupt_backup"] = "Повреждённый файл сборок сохранён в: {0}",
        ["log.loader.version_not_specified"] = "❌ Не указана версия загрузчика",
        ["log.loader.unsupported"] = "❌ Загрузчик {0} не поддерживается.",
        ["log.loader.minecraft_first"] = "❌ Сначала нужно скачать Minecraft {0}",
        ["log.loader.already_installed"] = "✅ {0} {1} для {2} уже установлен",
        ["log.loader.installing"] = "🔨 Установка {0} {1} для Minecraft {2}...",
        ["log.loader.downloading_installer"] = "⬇️ Скачивание {0} Installer...",
        ["log.loader.installer_exit_code"] = "⚠️ {0} Installer завершился с кодом {1}",
        ["log.loader.installed"] = "✅ {0} {1} установлен",
        ["log.loader.installed_resolved"] = "✅ {0} {1} установлен ({2})",
        ["log.loader.installer_no_profile"] = "❌ {0} Installer не создал профиль версии",
        ["log.loader.install_error"] = "❌ Ошибка установки {0}: {1}",
        ["log.loader.fabric_installing"] = "🧵 Установка Fabric {0} для Minecraft {1}...",
        ["log.loader.quilt_installing"] = "🧵 Установка Quilt {0} для Minecraft {1}...",
        ["log.loader.installer_fallback"] = "⚠️ Installer не сработал, скачиваем профиль напрямую...",
        ["log.loader.running_installer"] = "⚙️ Запуск {0} Installer...",
        ["log.loader.installer_warning"] = "⚠️ {0} Installer: {1}",
        ["log.loader.invalid_version_jar"] = "Файл версии отсутствует или повреждён: {0}",
        ["log.loader.quilt_installer_version_error"] = "❌ Не удалось получить версию Quilt Installer",
        ["log.loader.launcher_profiles_created"] = "📄 Создан launcher_profiles.json для установщика",
        ["log.fabric.already_installed"] = "✅ Fabric API уже установлен",
        ["log.fabric.downloading"] = "📥 Загрузка Fabric API...",
        ["log.fabric.not_found"] = "⚠️ Fabric API не найден для этой версии MC",
        ["log.fabric.url_not_found"] = "⚠️ Не удалось получить ссылку на Fabric API",
        ["log.fabric.installed"] = "✅ Fabric API установлен: {0}",
        ["log.fabric.error"] = "⚠️ Fabric API: {0}",
        ["log.session_start"] = "=== Сессия лаунчера ===",
        ["log.game_saved"] = "Сохранён лог игры: {0}",
        ["log.install_saved"] = "Сохранён лог установки: {0}",
        ["log.settings.load_error"] = "Ошибка загрузки настроек: {0}",
        ["log.settings.save_error"] = "Ошибка сохранения настроек: {0}",
    };

    private LocalizationService() { }

    public static void Initialize(string? setting)
    {
        Instance.ApplySetting(setting ?? "auto");
    }

    public void ApplySetting(string setting)
    {
        Setting = string.IsNullOrWhiteSpace(setting) ? "auto" : setting.Trim().ToLowerInvariant();
        _effective = ResolveEffectiveLanguage(Setting);
        NotifyChanged();
    }

    public static string ResolveEffectiveLanguage(string setting)
    {
        if (setting is "en" or "ru")
            return setting;

        var culture = CultureInfo.CurrentUICulture;
        return culture.TwoLetterISOLanguageName.Equals("ru", StringComparison.OrdinalIgnoreCase) ? "ru" : "en";
    }

    public string Get(string key)
    {
        var table = _effective == "ru" ? Ru : En;
        if (table.TryGetValue(key, out var value))
            return value;
        return En.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public string Format(string key, params object[] args) =>
        string.Format(Get(key), args);

    public static string T(string key) => Instance.Get(key);

    public static string F(string key, params object[] args) => Instance.Format(key, args);

    private void NotifyChanged()
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
        LanguageChanged?.Invoke();
    }
}
