param(
    [string]$Repo = "",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

if ([string]::IsNullOrWhiteSpace($Repo)) {
    $url = git -C $root config --get remote.origin.url 2>$null
    if ($url -match 'github\.com[:/](.+?)(?:\.git)?$') {
        $Repo = $matches[1].Trim().TrimEnd('/')
    }
}

if ([string]::IsNullOrWhiteSpace($Repo) -and $env:GITHUB_REPOSITORY) {
    $Repo = $env:GITHUB_REPOSITORY.Trim()
}

if ([string]::IsNullOrWhiteSpace($Repo)) {
    $Repo = "Festov/apeiron-launcher"
}

$escaped = $Repo.Replace('"', '\"')
$content = @"
// <auto-generated />
namespace Apeiron.Services;

public static class LauncherMetadata
{
    public const string GitHubRepository = "$escaped";
    public static bool HasUpdateSource => !string.IsNullOrWhiteSpace(GitHubRepository);
}
"@

$dir = Split-Path -Parent $OutputPath
if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

Set-Content -Path $OutputPath -Value $content -Encoding UTF8
