// <auto-generated />
namespace Apeiron.Services;

public static class LauncherMetadata
{
    public const string GitHubRepository = "Festov/apeiron-launcher";
    public static bool HasUpdateSource => !string.IsNullOrWhiteSpace(GitHubRepository);
}
